SIGUSR2 on latency change

diff --git a/modules/lua/test/script_runner b/modules/lua/test/script_runner
--- a/modules/lua/test/script_runner
+++ b/modules/lua/test/script_runner
@@ -3,3 +3,6 @@
 lua ./test_swig_api.lua
 if [ $? -ne 0 ]; then echo "$0 failed"; exit 1; fi
 
+lua ./test_latency_callback.lua
+if [ $? -ne 0 ]; then echo "$0 failed"; exit 1; fi
+
diff --git a/modules/perl/example-clients/script_runner b/modules/perl/example-clients/script_runner
--- a/modules/perl/example-clients/script_runner
+++ b/modules/perl/example-clients/script_runner
@@ -2,6 +2,12 @@
 
 export DYLD_LIBRARY_PATH=../.libs:.:$DYLD_LIBRARY_PATH
 
-perl ./latency_api.pl
+#perl ./latency_api.pl
+#if [ $? -ne 0 ]; then echo "$0 failed"; exit 1; fi
+
+perl ./latency_callback.pl
 if [ $? -ne 0 ]; then echo "$0 failed"; exit 1; fi
+
+#perl ./latency_by_type_api.pl
+#if [ $? -ne 0 ]; then echo "$0 failed"; exit 1; fi
 
